services:
  - type: web
    name: signal-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TWELVE_API_KEY
        value: "307e3dc7c3a7470791e495e03c4a5c88"
